"""add payments table and booking payment status

Revision ID: cd1917cdad66
Revises: 5d42504544c1
Create Date: 2026-07-22 09:01:52.602907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd1917cdad66'
down_revision: Union[str, Sequence[str], None] = '5d42504544c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Note: the ix_hotels_embedding_hnsw drop/recreate that autogenerate
    # detected here is a false positive (same as bdeba019efb4) -- that index
    # is created via raw SQL in the initial migration, not declared as
    # SQLAlchemy metadata, so it's intentionally omitted from this migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.Enum('card', 'promptpay', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'successful', 'failed', 'expired', 'refunded', name='payment_status'), nullable=False),
    sa.Column('provider_charge_id', sa.String(length=64), nullable=True),
    sa.Column('qr_image_url', sa.String(length=512), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider_charge_id'), 'payments', ['provider_charge_id'], unique=False)
    # Unlike the enums above (created implicitly by create_table), a bare
    # ALTER TABLE ADD COLUMN needs the enum type created explicitly first.
    booking_payment_status = postgresql.ENUM(
        'unpaid', 'pending', 'paid', 'failed', name='booking_payment_status'
    )
    booking_payment_status.create(op.get_bind())
    op.add_column('bookings', sa.Column('payment_status', booking_payment_status, nullable=False, server_default='unpaid'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_status')
    postgresql.ENUM(name='booking_payment_status').drop(op.get_bind())
    op.drop_index(op.f('ix_payments_provider_charge_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
